### ISSUE TITLE
Unable to create namespace

### ISSUE THREAD

**Issue by karthikaskannan** [upbound/provider-vault#12]
### What happened?

Unable to create vault namespace getting "Resource not found error"

Epic #

### How can we reproduce it?

apiVersion: vault.vault.upbound.io/v1alpha1
kind: Namespace
metadata:
  name: vault-namespace
spec:
  forProvider:
    namespace: "<Namespace>"
    path: "<PATH>"

**Comment by jaylevin** [comment]
I opened a PR that fixes this bug (#35) by renaming the `Namespace` MR to `VaultNamespace`. Something about it being named `Namespace` seems to be causing issues but the root cause is still not obvious to me..
